version: "3.9"

services:
  sql-fiap-hackaton-simulation:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-fiap-hackaton-simulation
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NovaSenhaForte123!"
      MSSQL_PID: "Developer"
    ports:
      - "14332:1433"
    volumes:
      - sql_fiap_hackaton_simulation_data:/var/opt/mssql

  rabbitmq-fiap-hackaton:
    image: rabbitmq:3-management
    container_name: rabbitmq-fiap-hackaton
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_fiap_hackaton_data:/var/lib/rabbitmq
    restart: unless-stopped

  api-fiap-hackaton:
    build: .
    container_name: api-fiap-hackaton
    depends_on:
      - sql-fiap-hackaton-simulation
      - rabbitmq-fiap-hackaton
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

volumes:
  sql_fiap_hackaton_simulation_data:
  rabbitmq_fiap_hackaton_data: