apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-api
  template:
    metadata:
      labels:
        app: fiap-api
    spec:
      containers:
        - name: fiap-api
          image: fiap-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sql-server,1433;Database=fiap-hackaton-simulation;User Id=sa;Password=NovaSenhaForte123!;TrustServerCertificate=True;Encrypt=False;"
            - name: RabbitMq__Host
              value: "rabbitmq"
            - name: RabbitMq__Port
              value: "5672"
            - name: RabbitMq__Username
              value: "admin"
            - name: RabbitMq__Password
              value: "admin123"
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-api
spec:
  type: NodePort
  selector:
    app: fiap-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007